from django.contrib.auth import get_user_model
from rest_framework import status
from rest_framework.test import APITestCase

from apps.catalog.models import Category
from apps.roles.models import Role

User = get_user_model()


class CategoryAPITests(APITestCase):
    @classmethod
    def setUpTestData(cls):
        role = Role.objects.get(code='customer')
        cls.user = User.objects.create_user(
            username='plain', email='plain@x.com', password='x', role=role,
        )
        cls.staff = User.objects.create_user(
            username='staff', email='staff@x.com', password='x', is_staff=True, role=role,
        )
        cls.beverages = Category.objects.create(
            name='Beverages', description='drinks and refreshments',
        )
        cls.snacks = Category.objects.create(name='Snacks', description='salty bites')
        cls.hidden = Category.objects.create(name='Hidden', is_active=False)
        cls.list_url = '/api/v1/categories/'

    def detail_url(self, pk):
        return f'/api/v1/categories/{pk}/'

    # --- read / visibility ---

    def test_list_public_and_paginated(self):
        response = self.client.get(self.list_url)
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertIn('count', response.data)
        self.assertIn('results', response.data)

    def test_anonymous_does_not_see_inactive(self):
        response = self.client.get(self.list_url)
        names = [r['name'] for r in response.data['results']]
        self.assertNotIn('Hidden', names)

    def test_anonymous_detail_of_inactive_is_404(self):
        response = self.client.get(self.detail_url(self.hidden.pk))
        self.assertEqual(response.status_code, status.HTTP_404_NOT_FOUND)

    def test_staff_sees_inactive_and_can_filter(self):
        self.client.force_authenticate(self.staff)
        response = self.client.get(self.list_url, {'is_active': 'false'})
        names = [r['name'] for r in response.data['results']]
        self.assertEqual(names, ['Hidden'])

    def test_filter_by_name_icontains(self):
        response = self.client.get(self.list_url, {'name': 'bev'})
        names = [r['name'] for r in response.data['results']]
        self.assertEqual(names, ['Beverages'])

    def test_search_on_description(self):
        response = self.client.get(self.list_url, {'search': 'salty'})
        names = [r['name'] for r in response.data['results']]
        self.assertEqual(names, ['Snacks'])

    # --- write / permissions ---

    def test_create_requires_token(self):
        response = self.client.post(self.list_url, {'name': 'New'})
        self.assertEqual(response.status_code, status.HTTP_401_UNAUTHORIZED)

    def test_create_forbidden_for_non_staff(self):
        self.client.force_authenticate(self.user)
        response = self.client.post(self.list_url, {'name': 'New'})
        self.assertEqual(response.status_code, status.HTTP_403_FORBIDDEN)

    def test_create_ok_for_staff_autogenerates_slug(self):
        self.client.force_authenticate(self.staff)
        response = self.client.post(self.list_url, {'name': 'Fresh Produce'})
        self.assertEqual(response.status_code, status.HTTP_201_CREATED)
        self.assertEqual(response.data['slug'], 'fresh-produce')

    def test_create_rejects_duplicate_name(self):
        self.client.force_authenticate(self.staff)
        response = self.client.post(self.list_url, {'name': 'Beverages'})
        self.assertEqual(response.status_code, status.HTTP_400_BAD_REQUEST)

    def test_create_rejects_duplicate_slug(self):
        self.client.force_authenticate(self.staff)
        response = self.client.post(self.list_url, {'name': 'Other', 'slug': 'beverages'})
        self.assertEqual(response.status_code, status.HTTP_400_BAD_REQUEST)
        self.assertIn('slug', response.data)

    def test_create_rejects_autogenerated_slug_collision_with_400(self):
        """A name that slugifies onto an existing slug must return 400, not 500."""
        Category.objects.create(name='Cafe')
        self.client.force_authenticate(self.staff)
        response = self.client.post(self.list_url, {'name': 'Café'})
        self.assertEqual(response.status_code, status.HTTP_400_BAD_REQUEST)
        self.assertIn('slug', response.data)

    def test_patch_slug_to_free_value(self):
        self.client.force_authenticate(self.staff)
        response = self.client.patch(
            self.detail_url(self.snacks.pk), {'slug': 'snack-bar'},
        )
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.snacks.refresh_from_db()
        self.assertEqual(self.snacks.slug, 'snack-bar')

    def test_patch_forbidden_for_non_staff(self):
        self.client.force_authenticate(self.user)
        response = self.client.patch(self.detail_url(self.snacks.pk), {'name': 'X'})
        self.assertEqual(response.status_code, status.HTTP_403_FORBIDDEN)

    def test_delete_by_staff(self):
        self.client.force_authenticate(self.staff)
        response = self.client.delete(self.detail_url(self.snacks.pk))
        self.assertEqual(response.status_code, status.HTTP_204_NO_CONTENT)
        self.assertFalse(Category.objects.filter(pk=self.snacks.pk).exists())
        self.assertIsNotNone(Category.all_objects.get(pk=self.snacks.pk).deleted_at)
        detail = self.client.get(self.detail_url(self.snacks.pk))
        self.assertEqual(detail.status_code, status.HTTP_404_NOT_FOUND)

    def test_recreate_a_soft_deleted_name_and_slug(self):
        self.client.force_authenticate(self.staff)
        self.client.delete(self.detail_url(self.beverages.pk))
        response = self.client.post(self.list_url, {'name': 'Beverages'})
        self.assertEqual(response.status_code, status.HTTP_201_CREATED)
        self.assertEqual(response.data['slug'], 'beverages')
