from django.db import IntegrityError
from django.test import TestCase

from apps.catalog.models import Category


class CategoryModelTests(TestCase):
    def test_slug_is_autogenerated_from_name(self):
        category = Category.objects.create(name='Hot Beverages')
        self.assertEqual(category.slug, 'hot-beverages')

    def test_explicit_slug_is_kept(self):
        category = Category.objects.create(name='Beverages', slug='drinks')
        self.assertEqual(category.slug, 'drinks')

    def test_name_is_unique(self):
        Category.objects.create(name='Beverages')
        with self.assertRaises(IntegrityError):
            Category.objects.create(name='Beverages')

    def test_slug_is_unique(self):
        Category.objects.create(name='Beverages', slug='shared')
        with self.assertRaises(IntegrityError):
            Category.objects.create(name='Snacks', slug='shared')

    def test_autogenerated_slug_collision_raises_integrity_error(self):
        """Outside the API two names that slugify equal collide at the DB level (documented ceiling)."""
        Category.objects.create(name='Cafe')
        with self.assertRaises(IntegrityError):
            Category.objects.create(name='Café')

    def test_str_returns_name(self):
        self.assertEqual(str(Category(name='Beverages')), 'Beverages')

    def test_active_queryset_excludes_inactive(self):
        Category.objects.create(name='Visible', is_active=True)
        Category.objects.create(name='Hidden', is_active=False)
        self.assertEqual(
            list(Category.objects.active().values_list('name', flat=True)),
            ['Visible'],
        )

    def test_active_composes_with_alive(self):
        category = Category.objects.create(name='Active Dead', is_active=True)
        category.delete()
        self.assertNotIn(
            'Active Dead',
            Category.objects.active().values_list('name', flat=True),
        )
        self.assertIn(
            'Active Dead',
            Category.all_objects.dead().values_list('name', flat=True),
        )

    def test_soft_deleted_name_can_be_reused(self):
        category = Category.objects.create(name='Beverages')
        category.delete()
        revived = Category.objects.create(name='Beverages')
        self.assertIsNone(revived.deleted_at)
