# Generated by Django 6.1.1 on 2026-09-05 17:54

import apps.roles.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0002_seed_roles'),
        ('users', '0003_assign_default_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(default=apps.roles.models.get_default_role, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='roles.role'),
        ),
    ]
