# Generated by Django 6.1.1 on 2026-09-05 18:53

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0002_seed_roles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'base_manager_name': 'all_objects', 'ordering': ['name']},
        ),
        migrations.AlterModelManagers(
            name='role',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='role',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='code',
            field=models.SlugField(max_length=32),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('code',), name='uniq_role_code_alive'),
        ),
    ]
